### ISSUE TITLE
Document Classification with Naive Bayes - Lab

### ISSUE THREAD

**Issue by deannagould** [learn-co-curriculum/dsc-document-classification-with-naive-bayes-lab#1]
## Issue Subtype

- [ ] Master branch code
- [x ] Solution branch code
- [ ] Code tests
- [ ] Layout/rendering issue
- [ ] Instructions unclear
- [ ] Other (explain below)

### Source

```

```

### Concern

last cell p_classes is not defined

## What OS Are You Using?

- [ ] OS X
- [x ] Windows
- [ ] WSL
- [ ] Linux
- [ ] Saturn Cloud from Canvas

**Comment by bpurdy-ds** [comment]
Hello. Since there is nothing described above and this content is now legacy content, I'll close the issue.
